#!/bin/sh

# A dmenu wrapper script for system functions.

cmds="\
lock		betterlockscreen -l
reboot	        reboot
shutdown	shutdown -Sh now"

choice="$(echo "$cmds" | cut -d'	' -f 1 | dmenu -p 'Do:')" || exit 1

`echo "$cmds" | grep "^$choice	" | cut -d '	' -f2-`
